services:
  postgres:
    image: postgres:18-alpine
    container_name: beaverp-postgres
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - beaverp

  pgadmin:
    image: dpage/pgadmin4
    container_name: beaverp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - beaverp

volumes:
  postgres_data:

networks:
  beaverp:
    driver: bridge
